Controllers/ClientePlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using APP_SECURITAS.Models;
using Newtonsoft.Json;

namespace APP_SECURITAS.Controllers
{
    public class ClientePlanController : Controller
    {
        // GET: ClientePlan
        string WURL = "http://localhost:63299/";
        public ActionResult Index()
        {
            UtlPlanes oUtlPlan = new UtlPlanes();
            ClientePlanes oCliPlan = new ClientePlanes();
            oCliPlan.LCbxClientes = oUtlPlan.FNComboCli();
            oCliPlan.LCbxPlanes = oUtlPlan.FNLLenaCombo(1);            
            return View(oCliPlan);
        }
        public async Task<ActionResult> ConsPlanes(FormCollection oForm) {
            ClientePlanes oCliPlan = new ClientePlanes();
            string WID = oForm["HDcbxCli"].ToString();
            List<ClientePlanes> oClientesPlanInfo = new List<ClientePlanes>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(WURL); client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync(string.Format("api/PlanCobD?nIDPlanCon={0}", WID));
                if (Res.IsSuccessStatusCode)
                {
                    var CliResponse = Res.Content.ReadAsStringAsync().Result;
                    oClientesPlanInfo = JsonConvert.DeserializeObject<List<ClientePlanes>>(CliResponse);
                }
                oCliPlan.IClientesPlanes = oClientesPlanInfo;
            }
            UtlPlanes oUtlPlan = new UtlPlanes();
            oCliPlan.LCbxPlanes = oUtlPlan.FNLLenaPLANDISP(int.Parse(WID));
            oCliPlan.LCbxClientes = oUtlPlan.FNComboCli(); oCliPlan.IDCli = int.Parse(WID);
            
            return View("Index", oCliPlan);
        }

        public ActionResult Guardar(FormCollection oForm) {            
            UtlPlanes oUtlPlan = new UtlPlanes();
            ClientePlanes oCliPlan = new ClientePlanes();

            int nIDPlan = int.Parse(oForm["IDPlan"].ToString());
            oCliPlan.IDPlan = nIDPlan;
            oCliPlan.IDCli = int.Parse(oForm["IDCli"].ToString());
            int IDCli = int.Parse(oForm["IDCli"].ToString());


            oCliPlan.LCbxPlanes = oUtlPlan.FNLLenaPLANDISP(nIDPlan);
            oCliPlan.LCbxClientes = oUtlPlan.FNComboCli(); oCliPlan.IDCli = IDCli;

            return View("Index", oCliPlan);
        }

    }
}

Views/ClientePlan/Index.cshtml
@model APP_SECURITAS.Models.ClientePlanes
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/Tls.js"></script>
    <script type="text/javascript">
        function SPSendCBX() {
            gEBI("HDcbxCli").value = gEBI("cbxCli").value;
            gEBI("Frm").action = "@Url.Action("ConsPlanes", "ClientePlan")"; gEBI("Frm").method = "post";
            gEBI("Frm").submit();
        }
        function FNGuardar() {
            if (!FNFrcWrt("cbxCli", "Favor de seleccionar un Cliente", "cbxCli")) return false;
            if (!FNFrcWrt("cbxPlan", "Favor de seleccionar un Plan", "cbxPlan")) return false;            
            gEBI("Frm").action = "@Url.Action("Guardar", "ClientePlan")"; gEBI("Frm").method = "post";
            gEBI("Frm").submit();
        }
    </script>
</head>
<body>
    <form id="Frm" name="Frm">
        <div>
            <h1>Cliente Con Planes.</h1>
            <div class="form-group">
                <label for="lUser">Selecciona un Cliente:</label>             
                @Html.DropDownListFor(m => m.IDCli, Model.LCbxClientes, "-- Selecciona una opción --", new { @class = "form-control", @id = "cbxCli", @onChange = "SPSendCBX();" })
            </div>
            <div class="form-group">
                <label for="sel1">Selecciona un Plan:</label>
                @Html.DropDownListFor(m => m.IDPlan, Model.LCbxPlanes, "-- Selecciona una opción --", new { @class = "form-control", @id = "cbxPlan" })
            </div>


            <br />
            <input type="button" id="btnAdd" name="btnAdd" class="btn alert-info" value="Agregar" onclick="return FNGuardar()" />
            <br /><br />
            <table id="tbl1" class="table table-bordered">
                <thead>
                    <tr>
                        <th>Planes</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <input type="hidden" id="HDEsGuardar" name="HDEsGuardar" value="0" />
        <input type="hidden" id="HDcbxCli" name="HDcbxCli" value="0" />
    </form>
</body>
</html>